#include "esp_wifi_downloader.h"

void writeDownloadsPath(FuriString* str, const char* fName) {
    furi_string_printf(str, "/data/%s", fName);
}

int create_file(ESPWifiDownloader* app) {
    Storage* storage = furi_record_open(RECORD_STORAGE);

    // Allocate file
    File* file = storage_file_alloc(storage);
    int code = 0;
    if(!storage_file_open(file, furi_string_get_cstr(app->fpath), FSAM_WRITE, FSOM_CREATE_ALWAYS)) {
        FURI_LOG_D(TAG, "Failed to open file");
        code = -1;
    }

    storage_file_close(file);
    storage_file_free(file);
    furi_record_close(RECORD_STORAGE);

    return code;
}

int append_file(ESPWifiDownloader* app) {
    Storage* storage = furi_record_open(RECORD_STORAGE);

    // Allocate file
    File* file = storage_file_alloc(storage);
    int code = 0;
    if(!storage_file_open(file, furi_string_get_cstr(app->fpath), FSAM_WRITE, FSOM_OPEN_APPEND)) {
        FURI_LOG_D(TAG, "Failed to append file");
        code = -1;
    } else
        storage_file_write(file, app->rx_buf, app->recv_bytes);

    storage_file_close(file);
    storage_file_free(file);
    furi_record_close(RECORD_STORAGE);

    return code;
}

void config_write(ESPWifiDownloader* app) {
    // Open storage
    Storage* storage = furi_record_open(RECORD_STORAGE);

    // Allocate file
    File* file = storage_file_alloc(storage);

    if(!storage_file_open(file, APP_DATA_PATH("cfg.txt"), FSAM_WRITE, FSOM_CREATE_ALWAYS)) {
        storage_file_free(file);
        furi_record_close(RECORD_STORAGE);
        storage_file_close(file);
        FURI_LOG_D(TAG, "Failed to open file ");
        return;
    }

    size_t ssid_len = strlen(app->ssid);
    size_t pwd_len = strlen(app->ssid);
    size_t total_len = ssid_len + pwd_len + 1;

    for(size_t i = 0; i < ssid_len; ++i) app->cfg_file_buf[i] = app->ssid[i];

    app->cfg_file_buf[ssid_len] = ':';
    for(size_t i = 0; i < pwd_len; ++i) app->cfg_file_buf[ssid_len + i + 1] = app->password[i];

    app->cfg_file_buf[total_len] = '\0';

    storage_file_write(file, app->cfg_file_buf, total_len);
    storage_file_close(file);
    storage_file_free(file);
    furi_record_close(RECORD_STORAGE);
}

/** main menu callback - sends a custom event to the scene manager based on the menu selection */
void esp_wifi_downloader_menu_callback_main_menu(void* context, uint32_t index) {
    FURI_LOG_T(TAG, "esp_wifi_downloader_menu_callback_main_menu");
    ESPWifiDownloader* app = context;
    switch(index) {
    case ESPWifiDownloaderMenuSelection_One:
        scene_manager_handle_custom_event(app->scene_manager, ESPWifiDownloaderEvent_ShowConfig);
        break;
    case ESPWifiDownloaderMenuSelection_Two:
        scene_manager_handle_custom_event(app->scene_manager, ESPWifiDownloaderEvent_ShowPopupTwo);
        break;
    }
}

/** resets the menu, gives it content, callbacks and selection enums */
void esp_wifi_downloader_scene_on_enter_main_menu(void* context) {
    FURI_LOG_T(TAG, "esp_wifi_downloader_scene_on_enter_main_menu");
    ESPWifiDownloader* app = context;
    submenu_reset(app->menu);
    submenu_set_header(app->menu, "ESP WiFi Downloader");

    // NB. icons are specified as NULL below, because:
    // * icons are _always_ animated by the menu
    // * the icons provided (&I_one, &I_two) are generated by the build process
    // * these icons do not have a framerate (resulting in a division by zero)
    submenu_add_item(
        app->menu,
        "Configure Wifi",
        ESPWifiDownloaderMenuSelection_One,
        esp_wifi_downloader_menu_callback_main_menu,
        app);
    submenu_add_item(
        app->menu,
        "Connect",
        ESPWifiDownloaderMenuSelection_Two,
        esp_wifi_downloader_menu_callback_main_menu,
        app);
    view_dispatcher_switch_to_view(app->view_dispatcher, ESPWifiDownloaderView_Menu);
}

/** main menu event handler - switches scene based on the event */
bool esp_wifi_downloader_scene_on_event_main_menu(void* context, SceneManagerEvent event) {
    FURI_LOG_T(TAG, "esp_wifi_downloader_scene_on_event_main_menu");
    ESPWifiDownloader* app = context;

    bool consumed = false;
    switch(event.type) {
    case SceneManagerEventTypeCustom:
        switch(event.event) {
        case ESPWifiDownloaderEvent_ShowConfig:
            scene_manager_next_scene(app->scene_manager, ESPWifiDownloaderScene_Config);
            consumed = true;
            break;
        case ESPWifiDownloaderEvent_ShowPopupTwo:
            scene_manager_next_scene(app->scene_manager, ESPWifiDownloaderScene_SecondPopup);
            consumed = true;
            break;
        }
        break;
    default: // eg. SceneManagerEventTypeBack, SceneManagerEventTypeTick
        consumed = false;
        break;
    }
    return consumed;
}

void esp_wifi_downloader_scene_on_exit_main_menu(void* context) {
    FURI_LOG_T(TAG, "esp_wifi_downloader_scene_on_exit_main_menu");
    ESPWifiDownloader* app = context;
    submenu_reset(app->menu);
}

void esp_wifi_downloader_scene_config_var_list_change_callback(VariableItem* item) {
    FURI_LOG_T(TAG, "esp_wifi_downloader_scene_config_var_list_change_callback");
    furi_assert(item);

    ESPWifiDownloader* app = variable_item_get_context(item);
    furi_assert(app);

    uint8_t item_index = variable_item_get_current_value_index(item);
    furi_assert(item_index < CONFIG_ITEMS);
}

bool esp_wifi_downloader_text_input_validator(const char* text, FuriString* error, void* context) {
    FURI_LOG_T(TAG, "esp_wifi_downloader_text_input_validator");
    furi_assert(context);

    if(strlen(text) > ESP_WIFI_DOWNLOADER_TEXT_INPUT_STORE_SIZE) {
        furi_string_set_str(error, "value is too long");
        return false;
    }

    return true;
}

void esp_wifi_downloader_text_input_result_callback(void* context) {
    FURI_LOG_T(TAG, "esp_wifi_downloader_text_input_result_callback");
    furi_assert(context);
    ESPWifiDownloader* app = context;
    switch(app->selected_var) {
    case 0:
        FURI_LOG_T(TAG, "val: %s", app->ssid);
        if(strlen(app->password) != 0) config_write(app);
        break;
    case 1:
        FURI_LOG_T(TAG, "val: %s", app->password);
        if(strlen(app->ssid) != 0) config_write(app);
        break;
    }
}

void esp_wifi_downloader_scene_config_var_list_item_enter_callback(void* context, uint32_t index) {
    furi_assert(context);
    ESPWifiDownloader* app = context;
    FURI_LOG_T(TAG, "esp_wifi_downloader_scene_config_var_list_item_enter_callback");
    furi_assert(index < CONFIG_ITEMS);
    app->selected_var = index;
    text_input_reset(app->text_input);
    switch(index) {
    case 0:
        text_input_set_header_text(app->text_input, "SSID");
        text_input_set_result_callback(
            app->text_input,
            esp_wifi_downloader_text_input_result_callback,
            app,
            app->ssid,
            ESP_WIFI_DOWNLOADER_TEXT_INPUT_STORE_SIZE,
            true);
        break;
    case 1:
        text_input_set_header_text(app->text_input, "Password");
        text_input_set_result_callback(
            app->text_input,
            esp_wifi_downloader_text_input_result_callback,
            app,
            app->password,
            ESP_WIFI_DOWNLOADER_TEXT_INPUT_STORE_SIZE,
            true);
        break;
    }

    text_input_set_validator(app->text_input, esp_wifi_downloader_text_input_validator, app);
    scene_manager_next_scene(app->scene_manager, ESPWifiDownloaderScene_TextInput);
    view_dispatcher_switch_to_view(app->view_dispatcher, ESPWifiDownloaderView_TextInput);
}

void esp_wifi_downloader_scene_on_enter_config(void* context) {
    FURI_LOG_T(TAG, "esp_wifi_downloader_scene_on_enter_config");
    ESPWifiDownloader* app = context;
    variable_item_list_reset(app->var_item_list);

    VariableItem* item;
    const char* labels[] = {"Set SSID", "Set Password"};
    for(int i = 0; i < CONFIG_ITEMS; i++) {
        item = variable_item_list_add(
            app->var_item_list,
            labels[i],
            1,
            esp_wifi_downloader_scene_config_var_list_change_callback,
            app);
        if(i == 0)
            variable_item_set_current_value_text(item, app->ssid);
        else
            variable_item_set_current_value_text(item, app->password);
    }

    variable_item_list_set_enter_callback(
        app->var_item_list, esp_wifi_downloader_scene_config_var_list_item_enter_callback, app);

    view_dispatcher_switch_to_view(app->view_dispatcher, ESPWifiDownloaderView_VarItemList);
}

bool esp_wifi_downloader_scene_on_event_config(void* context, SceneManagerEvent event) {
    FURI_LOG_T(TAG, "esp_wifi_downloader_scene_on_event_config");
    UNUSED(context);
    UNUSED(event);
    return false; // don't handle any events
}

void esp_wifi_downloader_scene_on_exit_config(void* context) {
    FURI_LOG_T(TAG, "esp_wifi_downloader_scene_on_exit_config");
    ESPWifiDownloader* app = context;
    submenu_reset(app->menu);
}

/* popup 2 scene */

void handle_cmd(void* context) {
    ESPWifiDownloader* app = context;
    FuriString* cmd = furi_string_alloc();
    furi_string_printf(cmd, "%s", app->rx_buf);

    if(furi_string_equal_str(cmd, WIFI_INFO)) {
        app->expect_bytes = 1;
        app->expect_event = DataEventWiFiConnInfoSize;
    } else if(furi_string_equal_str(cmd, WL_NO_SSID_AVAIL)) {
        furi_string_printf(app->popup_text, "This SSID is not available");
        scene_manager_handle_custom_event(app->scene_manager, CMDPopupTextEvent_Update);
    } else if(furi_string_equal_str(cmd, WL_CONNECT_FAILED)) {
        furi_string_printf(app->popup_text, "WiFi connection failed");
        scene_manager_handle_custom_event(app->scene_manager, CMDPopupTextEvent_Update);
    } else if(furi_string_equal_str(cmd, WL_CONNECTION_LOST)) {
        furi_string_printf(app->popup_text, "WiFi connection lost");
        scene_manager_handle_custom_event(app->scene_manager, CMDPopupTextEvent_Update);
    } else if(furi_string_equal_str(cmd, WL_NO_SHIELD)) {
        furi_string_printf(app->popup_text, "No shield");
        scene_manager_handle_custom_event(app->scene_manager, CMDPopupTextEvent_Update);
    } else if(furi_string_equal_str(cmd, TRANSFER_BEGIN)) {
        app->expect_bytes = 1;
        app->expect_event = DataEventFileNameSize;
    } else if(furi_string_equal_str(cmd, FILE_PART)) {
        app->expect_bytes = 1;
        app->expect_event = DataEventFilePartSize;
    } else if(furi_string_equal_str(cmd, TRANSFER_END)) {
        furi_string_printf(app->popup_text, "Successfully written file");
        scene_manager_handle_custom_event(app->scene_manager, CMDPopupTextEvent_Update);
    }

    furi_string_free(cmd);
}

void handle_recv(void* context) {
    ESPWifiDownloader* app = context;

    switch(app->expect_event) {
    case DataEventCmd:
        app->rx_buf[app->recv_bytes] = '\0';
        handle_cmd(app);
        break;
    case DataEventWiFiConnInfoSize:
        app->expect_bytes = app->rx_buf[0];
        app->expect_event = DataEventWiFiConnInfo;
        break;
    case DataEventFileNameSize:
        app->expect_bytes = app->rx_buf[0];
        app->expect_event = DataEventFileName;
        break;
    case DataEventFilePartSize:
        app->expect_bytes = app->rx_buf[0];
        app->expect_event = DataEventFilePart;
        break;
    case DataEventWiFiConnInfo:
        app->rx_buf[app->recv_bytes] = '\0';
        app->expect_bytes = CMD_LEN;
        app->expect_event = DataEventCmd;
        furi_string_printf(app->popup_text, "Server address:\n%s", app->rx_buf);
        scene_manager_handle_custom_event(app->scene_manager, CMDPopupTextEvent_Update);
        break;
    case DataEventFileName:
        app->rx_buf[app->recv_bytes] = '\0';
        app->expect_bytes = CMD_LEN;
        app->expect_event = DataEventCmd;
        furi_string_printf(app->popup_text, "Receiving file: %s", app->rx_buf);
        scene_manager_handle_custom_event(app->scene_manager, CMDPopupTextEvent_Update);
        writeDownloadsPath(app->fpath, (const char*)app->rx_buf);
        create_file(app);
        break;
    case DataEventFilePart:
        app->expect_bytes = 1;
        app->expect_event = DataEventSum;
        append_file(app);
        break;
    case DataEventSum:
        app->expect_bytes = CMD_LEN;
        app->expect_event = DataEventCmd;
        // furi_hal_serial_tx(app->serial_handle, (uint8_t*)("ACK\n"), 4);
        break;
    default:
        break;
    }

    app->recv_bytes = 0;
}

static int32_t uart_worker(void* context) {
    ESPWifiDownloader* app = context;

    while(1) {
        uint32_t events =
            furi_thread_flags_wait(WORKER_ALL_RX_EVENTS, FuriFlagWaitAny, FuriWaitForever);
        furi_check((events & FuriFlagError) == 0);
        if(events & WorkerEvtStop) break;
        if(events & WorkerEvtRxDone) {
            size_t len = furi_stream_buffer_receive(
                app->rx_stream,
                app->rx_buf + app->recv_bytes,
                UART_BUFFER_SIZE - app->recv_bytes,
                FuriWaitForever);
            if(len > 0) {
                app->recv_bytes += len;
                if(app->recv_bytes >= app->expect_bytes) {
                    handle_recv(app);
                }
            }
        }
    }

    furi_stream_buffer_free(app->rx_stream);

    return 0;
}

void uart_terminal_uart_on_irq_cb(
    FuriHalSerialHandle* handle,
    FuriHalSerialRxEvent event,
    void* context) {
    ESPWifiDownloader* app = context;

    if(event == FuriHalSerialRxEventData) {
        uint8_t data = furi_hal_serial_async_rx(handle);
        furi_stream_buffer_send(app->rx_stream, &data, 1, 0);
        furi_thread_flags_set(furi_thread_get_id(app->rx_thread), WorkerEvtRxDone);
    }
}

void esp_wifi_downloader_scene_on_enter_popup_two(void* context) {
    ESPWifiDownloader* app = context;
    popup_reset(app->popup);
    popup_set_context(app->popup, app);
    if(strlen(app->cfg_file_buf) == 0) {
        popup_set_text(app->popup, "Configure wifi first", 64, 10, AlignCenter, AlignCenter);
        view_dispatcher_switch_to_view(app->view_dispatcher, ESPWifiDownloaderView_Popup);
        return;
    }

    popup_set_header(app->popup, "Connection Status", 64, 10, AlignCenter, AlignTop);
    popup_set_text(app->popup, "Trying to connect...", 64, 30, AlignCenter, AlignCenter);

    app->rx_stream = furi_stream_buffer_alloc(UART_BUFFER_SIZE, 1);
    app->rx_thread = furi_thread_alloc();
    app->popup_text = furi_string_alloc();
    app->fpath = furi_string_alloc();
    furi_thread_set_name(app->rx_thread, "ESPWifiDownloader_UartRxThread");
    furi_thread_set_stack_size(app->rx_thread, BUFSIZ);
    furi_thread_set_context(app->rx_thread, app);
    furi_thread_set_callback(app->rx_thread, uart_worker);
    furi_thread_start(app->rx_thread);

    app->serial_handle = furi_hal_serial_control_acquire(app->uart_ch);
    furi_check(app->serial_handle);
    furi_hal_serial_init(app->serial_handle, BAUDRATE);
    app->rx_init = true;

    furi_hal_serial_async_rx_start(app->serial_handle, uart_terminal_uart_on_irq_cb, app, false);
    furi_hal_serial_tx(app->serial_handle, (uint8_t*)("WSP\n"), 4);
    furi_hal_serial_tx(
        app->serial_handle, (uint8_t*)(app->cfg_file_buf), strlen(app->cfg_file_buf));
    furi_hal_serial_tx(app->serial_handle, (uint8_t*)("\n"), 1);
    view_dispatcher_switch_to_view(app->view_dispatcher, ESPWifiDownloaderView_Popup);
}

bool esp_wifi_downloader_scene_on_event_popup_two(void* context, SceneManagerEvent event) {
    ESPWifiDownloader* app = context;

    bool consumed = false;
    switch(event.type) {
    case SceneManagerEventTypeCustom:
        switch(event.event) {
        case CMDPopupTextEvent_Update:
            popup_set_text(
                app->popup,
                furi_string_get_cstr(app->popup_text),
                64,
                30,
                AlignCenter,
                AlignCenter);
            consumed = true;
            break;
        }
        break;
    default:
        consumed = false;
        break;
    }
    return consumed;
}

void esp_wifi_downloader_scene_on_exit_popup_two(void* context) {
    FURI_LOG_T(TAG, "esp_wifi_downloader_scene_on_exit_popup_two");
    ESPWifiDownloader* app = context;
    if(app->rx_init) {
        furi_hal_serial_async_rx_stop(app->serial_handle);
        furi_hal_serial_deinit(app->serial_handle);
        furi_hal_serial_control_release(app->serial_handle);

        furi_thread_flags_set(furi_thread_get_id(app->rx_thread), WorkerEvtStop);
        furi_thread_join(app->rx_thread);
        furi_thread_free(app->rx_thread);
        furi_string_free(app->popup_text);
        furi_string_free(app->fpath);
    }

    popup_reset(app->popup);
}

/** custom event handler - passes the event to the scene manager */
bool esp_wifi_downloader_scene_manager_custom_event_callback(void* context, uint32_t custom_event) {
    FURI_LOG_T(TAG, "esp_wifi_downloader_scene_manager_custom_event_callback");
    furi_assert(context);
    ESPWifiDownloader* app = context;
    return scene_manager_handle_custom_event(app->scene_manager, custom_event);
}

/** navigation event handler - passes the event to the scene manager */
bool esp_wifi_downloader_scene_manager_navigation_event_callback(void* context) {
    FURI_LOG_T(TAG, "esp_wifi_downloader_scene_manager_navigation_event_callback");
    furi_assert(context);
    ESPWifiDownloader* app = context;
    return scene_manager_handle_back_event(app->scene_manager);
}

/** initialise the views, and initialise the view dispatcher with all views */
void esp_wifi_downloader_view_dispatcher_init(ESPWifiDownloader* app) {
    FURI_LOG_T(TAG, "esp_wifi_downloader_view_dispatcher_init");
    app->view_dispatcher = view_dispatcher_alloc();
    view_dispatcher_enable_queue(app->view_dispatcher);

    // allocate each view
    FURI_LOG_D(TAG, "esp_wifi_downloader_view_dispatcher_init allocating views");
    app->menu = submenu_alloc();
    app->popup = popup_alloc();
    app->var_item_list = variable_item_list_alloc();
    app->text_input = text_input_alloc();

    // assign callback that pass events from views to the scene manager
    FURI_LOG_D(TAG, "esp_wifi_downloader_view_dispatcher_init setting callbacks");
    view_dispatcher_set_event_callback_context(app->view_dispatcher, app);
    view_dispatcher_set_custom_event_callback(
        app->view_dispatcher, esp_wifi_downloader_scene_manager_custom_event_callback);
    view_dispatcher_set_navigation_event_callback(
        app->view_dispatcher, esp_wifi_downloader_scene_manager_navigation_event_callback);

    // add views to the dispatcher, indexed by their enum value
    FURI_LOG_D(TAG, "esp_wifi_downloader_view_dispatcher_init adding view menu");
    view_dispatcher_add_view(
        app->view_dispatcher, ESPWifiDownloaderView_Menu, submenu_get_view(app->menu));
    FURI_LOG_D(TAG, "esp_wifi_downloader_view_dispatcher_init adding view var list");
    view_dispatcher_add_view(
        app->view_dispatcher,
        ESPWifiDownloaderView_VarItemList,
        variable_item_list_get_view(app->var_item_list));
    FURI_LOG_D(TAG, "esp_wifi_downloader_view_dispatcher_init adding view popup");
    view_dispatcher_add_view(
        app->view_dispatcher, ESPWifiDownloaderView_Popup, popup_get_view(app->popup));
    view_dispatcher_add_view(
        app->view_dispatcher,
        ESPWifiDownloaderView_TextInput,
        text_input_get_view(app->text_input));
}

/** free all app data, scene manager, and view dispatcher */
void esp_wifi_downloader_free(ESPWifiDownloader* app) {
    FURI_LOG_T(TAG, "esp_wifi_downloader_free");
    scene_manager_free(app->scene_manager);
    view_dispatcher_remove_view(app->view_dispatcher, ESPWifiDownloaderView_Menu);
    view_dispatcher_remove_view(app->view_dispatcher, ESPWifiDownloaderView_Popup);
    view_dispatcher_remove_view(app->view_dispatcher, ESPWifiDownloaderView_VarItemList);
    view_dispatcher_remove_view(app->view_dispatcher, ESPWifiDownloaderView_TextInput);
    view_dispatcher_free(app->view_dispatcher);

    submenu_free(app->menu);
    popup_free(app->popup);
    text_input_free(app->text_input);
    variable_item_list_free(app->var_item_list);
    free(app);
}

/** go to trace log level in the dev environment */
void esp_wifi_downloader_set_log_level() {
#ifdef FURI_DEBUG
    furi_log_set_level(FuriLogLevelTrace);
#else
    furi_log_set_level(FuriLogLevelInfo);
#endif
}

void esp_wifi_downloader_scene_text_input_callback(void* context) {
    FURI_LOG_T(TAG, "esp_wifi_downloader_scene_text_input_callback");
    furi_assert(context);
}

void esp_wifi_downloader_scene_text_input_on_enter(void* context) {
    FURI_LOG_T(TAG, "esp_wifi_downloader_scene_text_input_on_enter");
    ESPWifiDownloader* app = context;

    view_dispatcher_switch_to_view(app->view_dispatcher, ESPWifiDownloaderView_TextInput);
}

bool esp_wifi_downloader_scene_text_input_on_event(void* context, SceneManagerEvent event) {
    FURI_LOG_T(TAG, "esp_wifi_downloader_scene_text_input_on_event");
    furi_assert(context);
    bool consumed = false;

    if(event.type == SceneManagerEventTypeCustom) {
        consumed = true;
    }

    return consumed;
}

void esp_wifi_downloader_scene_text_input_on_exit(void* context) {
    ESPWifiDownloader* app = context;

    text_input_reset(app->text_input);
}

/** collection of all scene on_enter handlers - in the same order as their enum */
void (*const esp_wifi_downloader_scene_on_enter_handlers[])(void*) = {
    esp_wifi_downloader_scene_on_enter_main_menu,
    esp_wifi_downloader_scene_on_enter_config,
    esp_wifi_downloader_scene_text_input_on_enter,
    esp_wifi_downloader_scene_on_enter_popup_two};

/** collection of all scene on event handlers - in the same order as their enum */
bool (*const esp_wifi_downloader_scene_on_event_handlers[])(void*, SceneManagerEvent) = {
    esp_wifi_downloader_scene_on_event_main_menu,
    esp_wifi_downloader_scene_on_event_config,
    esp_wifi_downloader_scene_text_input_on_event,
    esp_wifi_downloader_scene_on_event_popup_two};

/** collection of all scene on exit handlers - in the same order as their enum */
void (*const esp_wifi_downloader_scene_on_exit_handlers[])(void*) = {
    esp_wifi_downloader_scene_on_exit_main_menu,
    esp_wifi_downloader_scene_on_exit_config,
    esp_wifi_downloader_scene_text_input_on_exit,
    esp_wifi_downloader_scene_on_exit_popup_two};

/** collection of all on_enter, on_event, on_exit handlers */
const SceneManagerHandlers esp_wifi_downloader_scene_event_handlers = {
    .on_enter_handlers = esp_wifi_downloader_scene_on_enter_handlers,
    .on_event_handlers = esp_wifi_downloader_scene_on_event_handlers,
    .on_exit_handlers = esp_wifi_downloader_scene_on_exit_handlers,
    .scene_num = ESPWifiDownloaderScene_count};

/** initialise the scene manager with all handlers */
void esp_wifi_downloader_scene_manager_init(ESPWifiDownloader* app) {
    FURI_LOG_T(TAG, "esp_wifi_downloader_scene_manager_init");
    app->scene_manager = scene_manager_alloc(&esp_wifi_downloader_scene_event_handlers, app);
}

void init_ssid_password_from_config(ESPWifiDownloader* app) {
    // Open storage
    Storage* storage = furi_record_open(RECORD_STORAGE);

    // Allocate file
    File* file = storage_file_alloc(storage);

    if(!storage_file_open(file, APP_DATA_PATH("cfg.txt"), FSAM_READ, FSOM_OPEN_EXISTING)) {
        storage_file_free(file);
        furi_record_close(RECORD_STORAGE);
        return;
    }

    int n = storage_file_read(file, app->cfg_file_buf, CFG_FILE_SIZE);
    int ssid_offset = 0;

    for(int i = 0; i < n; ++i) {
        if(app->cfg_file_buf[i] == ':') {
            app->ssid[i] = '\0';
            ssid_offset = i + 1;
            continue;
        }

        if(ssid_offset == 0)
            app->ssid[i] = app->cfg_file_buf[i];
        else
            app->password[i - ssid_offset] = app->cfg_file_buf[i];
    }

    storage_file_close(file);
    storage_file_free(file);
    furi_record_close(RECORD_STORAGE);
}

/** initialise app data, scene manager, and view dispatcher */
ESPWifiDownloader* esp_wifi_downloader_init() {
    FURI_LOG_T(TAG, "esp_wifi_downloader_init");
    ESPWifiDownloader* app = malloc(sizeof(ESPWifiDownloader));
    app->expect_bytes = CMD_LEN;
    app->expect_event = DataEventCmd;

    init_ssid_password_from_config(app);
    esp_wifi_downloader_scene_manager_init(app);
    esp_wifi_downloader_view_dispatcher_init(app);
    return app;
}

/** entrypoint */
int32_t esp_wifi_downloader_app(void* p) {
    UNUSED(p);
    esp_wifi_downloader_set_log_level();

    // create the app context struct, scene manager, and view dispatcher
    FURI_LOG_I(TAG, "Test app starting...");
    ESPWifiDownloader* app = esp_wifi_downloader_init();

    // set the scene and launch the main loop
    Gui* gui = furi_record_open(RECORD_GUI);
    view_dispatcher_attach_to_gui(app->view_dispatcher, gui, ViewDispatcherTypeFullscreen);
    scene_manager_next_scene(app->scene_manager, ESPWifiDownloaderScene_MainMenu);
    FURI_LOG_D(TAG, "Starting dispatcher...");
    view_dispatcher_run(app->view_dispatcher);

    // free all memory
    FURI_LOG_I(TAG, "Test app finishing...");
    furi_record_close(RECORD_GUI);
    esp_wifi_downloader_free(app);
    return 0;
}
